version: '3.7'

services:
  app:
    build: ./
    container_name: mnist-generator
    image: s1sharp/mnist-generator
    ports:
      - 5000:5000
    environment:
          - APP_VERSION_ENV=release
    restart: on-failure
    command: "python web_app/app.py $APP_VERSION_ENV"
